(function () {
 if (typeof window === 'undefined') return;

  function getEnemyCatalog(gameImages) {
   const GAME_IMAGES = gameImages || {};
   return [
    {
     id: 'slime',
     name: 'スライム',
     levelText: 'Lv1〜4',
     image: GAME_IMAGES.img_014,
     description: '基礎的な攻撃と防御を使う、序盤の敵です。',
     passives: [],
     skills: ['弱攻撃', '攻撃', '防御', 'スライムタックル', 'スライム強打', '暴走スライム'],
    },
    {
     id: 'goblin',
     name: 'ゴブリン',
     levelText: 'Lv1〜4',
     image: GAME_IMAGES.img_023,
     description: '軽い攻撃と防御を使い分ける、序盤向けの小型の敵です。',
     passives: [],
     skills: ['小突き', '粗末な盾', '棍棒打ち', '守りの構え', 'ゴブリンラッシュ'],
    },
    {
     id: 'bat',
     name: 'バット',
     levelText: 'Lv1〜4',
     image: GAME_IMAGES.img_024,
     description: '吸血で粘り強く戦う、序盤向けの飛行系の敵です。',
     passives: [],
     skills: ['吸血', '羽ばたき', '急降下', 'かく乱飛行', '夜襲'],
    },
    {
     id: 'wolf',
     name: 'ウルフ',
     levelText: 'Lv5〜8',
     image: GAME_IMAGES.img_013,
     description: '攻撃寄りの行動が多い、素早い敵です。',
     passives: [],
     skills: ['かみつき', '身構える', '遠吠え', '連続かみつき', 'ハウリングラッシュ'],
    },
    {
     id: 'orc',
     name: 'オーク',
     levelText: 'Lv5〜8',
     image: GAME_IMAGES.img_025,
     description: '高めの防御と重い一撃で攻めてくる、中盤のパワー型の敵です。',
     passives: [],
     skills: ['重い棍棒', '厚い皮膚', 'オークスマッシュ', '踏みならし', '剛腕クラッシュ', '仁王立ち'],
    },
    {
     id: 'shaman',
     name: 'シャーマン',
     levelText: 'Lv5〜8',
     image: GAME_IMAGES.img_026,
     description: '攻撃・防御に加えて麻痺を使う、中盤の妨害型の敵です。',
     passives: [],
     skills: ['呪いの火', '精霊の守り', '呪術弾', '魔力障壁', 'シャーマンブラスト'],
    },
   {
    id: 'mage',
    name: '魔導士',
    levelText: 'Lv9〜12',
    image: GAME_IMAGES.img_012,
     description: '魔法攻撃と麻痺で妨害してくる敵です。',
     passives: [],
     skills: ['ダークボルト', '魔力障壁', '呪術弾', 'パラライズボルト', '闇の波動', 'アビスノヴァ'],
    },
    {
     id: 'rune_guardian',
     name: 'ルーンガーディアン',
     levelText: 'Lv9〜12',
     image: GAME_IMAGES.img_027,
     description: '堅い結界と中威力の斬撃で粘り強く戦う、中盤の防御寄りの敵です。',
     passives: [],
     skills: ['ルーンスラッシュ', '刻印の盾', '守護刻印', 'ルーンブレイク', '古代の一閃', '堅牢結界'],
    },
    {
     id: 'storm_adept',
     name: 'ストームアデプト',
     levelText: 'Lv9〜12',
     image: GAME_IMAGES.img_028,
     description: '雷撃と麻痺で手札操作を妨害する、中盤の特殊攻撃寄りの敵です。',
     passives: [],
     skills: ['スパークショット', '帯電ガード', 'ライトニングピン', '雷撃連鎖', 'サンダーバースト', '雷光槍'],
    },
    {
     id: 'ice_golem',
     name: 'アイスゴーレム',
     levelText: 'Lv13〜16',
     image: GAME_IMAGES.ice_golem,
     description: '高い防御と凍結で手札操作を封じる重量級の敵です。',
     passives: [],
     skills: ['氷塊パンチ', 'アイスアーマー', 'フロストブレス', 'グレイシャースラム', '永久凍土の壁', 'ブリザードクラッシュ'],
    },
    {
     id: 'crystal_serpent',
     name: 'クリスタルサーペント',
     levelText: 'Lv13〜16',
     image: GAME_IMAGES.img_029,
     description: '鋭い水晶の牙と凍結攻撃を使う、終盤手前の技巧型の敵です。',
     passives: [],
     skills: ['クリスタルバイト', '水晶の鱗', 'コールドファング', '水晶尾撃', '凍晶乱舞', '鋭晶突き'],
    },
    {
     id: 'stone_titan',
     name: 'ストーンタイタン',
     levelText: 'Lv13〜16',
     image: GAME_IMAGES.img_030,
     description: '重い打撃と高い防御で押し切る、終盤手前の耐久型の敵です。',
     passives: [],
     skills: ['岩石拳', '岩盤ガード', '踏み鳴らし', '巨石の構え', 'タイタンブロウ', '大地の城壁'],
    },
    {
     id: 'shadow_knight',
     name: 'シャドウナイト',
     levelText: 'Lv17〜19',
     image: GAME_IMAGES.shadow_knight,
     description: '高火力の斬撃と盾を使う、ボス前の強敵です。',
     passives: ['麻痺無効'],
     skills: ['ダークスラッシュ', '影の構え', 'ブラッドブレード', '影連斬', 'ナイトメアエッジ', '深淵の盾'],
    },
    {
     id: 'abyss_reaper',
     name: 'アビスリーパー',
     levelText: 'Lv17〜19',
     image: GAME_IMAGES.img_031,
     description: '鋭い鎌の連撃と軽い麻痺で攻める、ボス前の攻撃型の敵です。',
     passives: [],
     skills: ['アビスサイズ', '黒衣の防壁', '魂刈り', '悪夢の鎌', '深淵斬り', 'リーパーエッジ', '魂縛り'],
    },
    {
     id: 'obsidian_warden',
     name: 'オブシディアンウォーデン',
     levelText: 'Lv17〜19',
     image: GAME_IMAGES.img_032,
     description: '黒曜の圧力でリロードを鈍らせ、硬い守りと重い打撃で迫る妨害型の敵です。',
     passives: ['プレイヤーのリロード時間+2秒'],
     skills: ['黒曜拳', '黒曜の盾', '重圧の一撃', '要塞姿勢', '粉砕打', '黒曜城壁', 'ガーディアンブロウ'],
    },
    {
     id: 'void_knight',
     name: '深淵騎士ヴォイド',
     levelText: 'Lv20',
     image: GAME_IMAGES.img_009,
     phaseImages: [
      { label: '第1形態', src: GAME_IMAGES.img_009 },
      { label: '第2形態', src: GAME_IMAGES.void_phase2 },
     ],
     description: 'ステージ1のボス。撃破後に暴走形態として復活します。',
     passives: ['凍結無効', '第2形態復活'],
     skills: ['ヴォイドスラッシュ', '深淵の波動', '闇の構え', '崩壊斬', '虚無の浄化', '虚無連斬', 'ナイトメアレイド', 'アビスブレイク'],
    },
   ];
  }

 window.GameEnemies = {
  getEnemyCatalog,
 };
}());
