(function () {
 if (typeof window === 'undefined') return;

  function getEnemyCatalog(gameImages) {
   const GAME_IMAGES = gameImages || {};
   return [
    {
     id: 'slime',
     name: 'スライム',
     levelText: 'Lv1〜4',
     image: GAME_IMAGES.img_014,
     description: '基礎的な攻撃と防御を使う、序盤の敵です。',
     passives: [],
     skills: ['弱攻撃', '攻撃', '防御', 'スライムタックル', 'スライム強打', '暴走スライム'],
    },
    {
     id: 'goblin',
     name: 'ゴブリン',
     levelText: 'Lv1〜4',
     image: GAME_IMAGES.img_023,
     description: '軽い攻撃と防御を使い分ける、序盤向けの小型の敵です。',
     passives: [],
     skills: ['小突き', '粗末な盾', '棍棒打ち', '守りの構え', 'ゴブリンラッシュ'],
    },
    {
     id: 'bat',
     name: 'バット',
     levelText: 'Lv1〜4',
     image: GAME_IMAGES.img_024,
     description: '吸血で粘り強く戦う、序盤向けの飛行系の敵です。',
     passives: [],
     skills: ['吸血', '羽ばたき', '急降下', 'かく乱飛行', '夜襲'],
    },
    {
     id: 'wolf',
     name: 'ウルフ',
     levelText: 'Lv5〜8',
     image: GAME_IMAGES.img_013,
     description: '攻撃寄りの行動が多い、素早い敵です。',
     passives: [],
     skills: ['かみつき', '身構える', '遠吠え', '連続かみつき', 'ハウリングラッシュ'],
    },
    {
     id: 'orc',
     name: 'オーク',
     levelText: 'Lv5〜8',
     image: GAME_IMAGES.img_025,
     description: '高めの防御と重い一撃で攻めてくる、中盤のパワー型の敵です。',
     passives: [],
     skills: ['重い棍棒', '厚い皮膚', 'オークスマッシュ', '踏みならし', '剛腕クラッシュ', '仁王立ち'],
    },
    {
     id: 'shaman',
     name: 'シャーマン',
     levelText: 'Lv5〜8',
     image: GAME_IMAGES.img_026,
     description: '攻撃・防御に加えて麻痺を使う、中盤の妨害型の敵です。',
     passives: [],
     skills: ['呪いの火', '精霊の守り', '呪術弾', '魔力障壁', 'シャーマンブラスト'],
    },
   {
    id: 'mage',
    name: '魔導士',
    levelText: 'Lv9〜12',
    image: GAME_IMAGES.img_012,
     description: '魔法攻撃と麻痺で妨害してくる敵です。',
     passives: [],
     skills: ['ダークボルト', '魔力障壁', '呪術弾', 'パラライズボルト', '闇の波動', 'アビスノヴァ'],
    },
    {
     id: 'rune_guardian',
     name: 'ルーンガーディアン',
     levelText: 'Lv9〜12',
     image: GAME_IMAGES.img_027,
     description: '堅い結界と中威力の斬撃で粘り強く戦う、中盤の防御寄りの敵です。',
     passives: [],
     skills: ['ルーンスラッシュ', '刻印の盾', '守護刻印', 'ルーンブレイク', '古代の一閃', '堅牢結界'],
    },
    {
     id: 'storm_adept',
     name: 'ストームアデプト',
     levelText: 'Lv9〜12',
     image: GAME_IMAGES.img_028,
     description: '雷撃と麻痺で手札操作を妨害する、中盤の特殊攻撃寄りの敵です。',
     passives: [],
     skills: ['スパークショット', '帯電ガード', 'ライトニングピン', '雷撃連鎖', 'サンダーバースト', '雷光槍'],
    },
    {
     id: 'ice_golem',
     name: 'アイスゴーレム',
     levelText: 'Lv13〜16',
     image: GAME_IMAGES.ice_golem,
     description: '高い防御と凍結で手札操作を封じる重量級の敵です。',
     passives: [],
     skills: ['氷塊パンチ', 'アイスアーマー', 'フロストブレス', 'グレイシャースラム', '永久凍土の壁', 'ブリザードクラッシュ'],
    },
    {
     id: 'crystal_serpent',
     name: 'クリスタルサーペント',
     levelText: 'Lv13〜16',
     image: GAME_IMAGES.img_029,
     description: '鋭い水晶の牙と凍結攻撃を使う、終盤手前の技巧型の敵です。',
     passives: [],
     skills: ['クリスタルバイト', '水晶の鱗', 'コールドファング', '水晶尾撃', '凍晶乱舞', '鋭晶突き'],
    },
    {
     id: 'stone_titan',
     name: 'ストーンタイタン',
     levelText: 'Lv13〜16',
     image: GAME_IMAGES.img_030,
     description: '重い打撃と高い防御で押し切る、終盤手前の耐久型の敵です。',
     passives: [],
     skills: ['岩石拳', '岩盤ガード', '踏み鳴らし', '巨石の構え', 'タイタンブロウ', '大地の城壁'],
    },
    {
     id: 'shadow_knight',
     name: 'シャドウナイト',
     levelText: 'Lv17〜19',
     image: GAME_IMAGES.shadow_knight,
     description: '高火力の斬撃と盾を使う、ボス前の強敵です。',
     passives: ['麻痺無効'],
     skills: ['ダークスラッシュ', '影の構え', 'ブラッドブレード', '影連斬', 'ナイトメアエッジ', '深淵の盾'],
    },
    {
     id: 'abyss_reaper',
     name: 'アビスリーパー',
     levelText: 'Lv17〜19',
     image: GAME_IMAGES.img_031,
     description: '鋭い鎌の連撃と軽い麻痺で攻める、ボス前の攻撃型の敵です。',
     passives: [],
     skills: ['アビスサイズ', '黒衣の防壁', '魂刈り', '悪夢の鎌', '深淵斬り', 'リーパーエッジ', '魂縛り'],
    },
    {
     id: 'obsidian_warden',
     name: 'オブシディアンウォーデン',
     levelText: 'Lv17〜19',
     image: GAME_IMAGES.img_032,
     description: '黒曜の圧力でリロードを鈍らせ、硬い守りと重い打撃で迫る妨害型の敵です。',
     passives: ['プレイヤーのリロード時間+2秒'],
     skills: ['黒曜拳', '黒曜の盾', '重圧の一撃', '要塞姿勢', '粉砕打', '黒曜城壁', 'ガーディアンブロウ'],
    },
    {
     id: 'undead_knight',
     name: '不死騎士',
     levelText: 'Lv9～',
     image: 'assets/enemies/undead_knight.webp',
     description: '一度だけ致死ダメージを耐える、粘り強い騎士です。',
     passiveIds: ['tenacity'],
     passives: ['執念'],
     skills: ['朽ちた剣', '不死の構え', '墓所の一撃'],
    },
    {
     id: 'powder_raider',
     name: '火薬荒らし',
     levelText: 'Lv9～',
     image: 'assets/enemies/powder_raider.webp',
     description: '爆弾耐性を持ち、プレイヤーにも爆弾を押し付ける敵です。',
     passiveIds: ['bomb_resist'],
     passives: ['爆弾耐性'],
     skills: ['火薬殴打', '爆弾投げ', '火薬隠れ'],
    },
    {
     id: 'frozen_wraith',
     name: '凍土の亡霊',
     levelText: 'Lv9～',
     image: 'assets/enemies/frozen_wraith.webp',
     description: '凍結耐性を持つ、冷気をまとう亡霊です。',
     passiveIds: ['freeze_resist'],
     passives: ['凍結耐性'],
     skills: ['冷気の爪', '霜の壁', '亡霊の一撃'],
    },
    {
     id: 'abyss_poisoner',
     name: 'アビスポイズナー',
     levelText: 'Lv9～',
     image: 'assets/enemies/abyss_poisoner.webp',
     description: '毒耐性を持ち、毒でプレイヤーを削る敵です。',
     passiveIds: ['poison_resist'],
     passives: ['毒耐性'],
     skills: ['毒針', '毒霧の守り', 'アビスニードル'],
    },
    {
     id: 'frost_worm',
     name: 'フロストワーム',
     levelText: 'Lv13～',
     image: 'assets/enemies/frost_worm.webp',
     description: '凍結耐性を持ち、凍結と火傷を使い分ける氷の魔物です。',
     passiveIds: ['freeze_resist'],
     passives: ['凍結耐性'],
     skills: ['フロストバイト', '熱裂き', '氷殻'],
    },
    {
     id: 'bomb_eater',
     name: 'ボムイーター',
     levelText: 'Lv13～',
     image: 'assets/enemies/bomb_eater.webp',
     description: '爆発エネルギーを喰らう、爆弾耐性持ちの魔物です。',
     passiveIds: ['bomb_resist'],
     passives: ['爆弾耐性'],
     skills: ['爆食い', '爆弾吐き', '装甲腹'],
    },
    {
     id: 'blood_hound',
     name: 'ブラッドハウンド',
     levelText: 'Lv13～',
     image: 'assets/enemies/blood_hound.webp',
     description: '瀕死になるほど凶暴化する獣です。',
     passiveIds: ['desperate'],
     passives: ['背水'],
     skills: ['血牙', '唸り構え', '裂傷突進'],
    },
    {
     id: 'lich_skull',
     name: 'リッチスカル',
     levelText: 'Lv13～',
     image: 'assets/enemies/lich_skull.webp',
     description: '執念で一度だけ耐えるアンデッドです。',
     passiveIds: ['tenacity'],
     passives: ['執念'],
     skills: ['骨の呪弾', '死霊障壁', 'リッチボルト'],
    },
    {
     id: 'death_reaper',
     name: 'デスリーパー',
     levelText: 'Lv17～',
     image: 'assets/enemies/death_reaper.webp',
     description: '執念で耐えた後、致命的な一撃を狙う死神です。',
     passiveIds: ['tenacity', 'fatal_power'],
     passives: ['執念', '致命強化'],
     skills: ['死神の鎌', '終末の構え', '致命の一閃'],
    },
    {
     id: 'frost_dragon',
     name: 'フロストドラゴン',
     levelText: 'Lv17～',
     image: 'assets/enemies/frost_dragon.webp',
     description: '凍結耐性と時魔術で長期戦に持ち込む氷竜です。',
     passiveIds: ['freeze_resist', 'time_magic'],
     passives: ['凍結耐性', '時魔術'],
     skills: ['竜の凍息', '時霜の鱗', '氷竜尾撃'],
    },
    {
     id: 'abyss_beast',
     name: 'アビスビースト',
     levelText: 'Lv17～',
     image: 'assets/enemies/abyss_beast.webp',
     description: 'HPが減るほど獰猛になる深淵の獣です。',
     passiveIds: ['desperate', 'blood_price'],
     passives: ['背水', '血の代償'],
     skills: ['獣爪', '血の咆哮', '深淵皮膚'],
    },
    {
     id: 'void_knight',
     name: '深淵騎士ヴォイド',
     levelText: 'Lv20',
     image: GAME_IMAGES.img_009,
     phaseImages: [
      { label: '第1形態', src: GAME_IMAGES.img_009 },
      { label: '第2形態', src: GAME_IMAGES.void_phase2 },
     ],
     description: 'ステージ1のボス。撃破後に暴走形態として復活します。',
     passives: ['凍結無効', '第2形態復活'],
     skills: ['ヴォイドスラッシュ', '深淵の波動', '闇の構え', '崩壊斬', '虚無の浄化', '虚無連斬', 'ナイトメアレイド', 'アビスブレイク'],
    },
   ];
  }

 window.GameEnemies = {
  getEnemyCatalog,
 };
}());
